### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by TheMaster3558** [TheMaster3558/Master-Selector#1]
We need a logo to add to our docs and README pages

**Comment by LyubomirT** [comment]
I think I can try to work on this issue. Can you please assign it to me, if it's okay?

**Comment by TheMaster3558** [comment]
> I think I can try to work on this issue. Can you please assign it to me, if it's okay?

Sure, I assigned it to you

**Comment by LyubomirT** [comment]
Thanks! @TheMaster3558 are there any preferences you have for the logo or do you have any specific requirements? Such as the color, the style, and the logo type?

**Comment by TheMaster3558** [comment]
I'm pretty open to anything as long as it is relatively simple. Although if you do decide to go past a lettermark and add a symbol, just make sure that the symbol is related to this library or VEX robotics in general. Also, I can adjust the color scheme of the docs to fit your logo. Just make sure that it would fit nicely where the bolded **Master-Selector** is on the top left of the [docs](https://themaster3558.github.io/Master-Selector/). 

Let me know if you have any questions with running the documentation locally to test the logo as I have not added any instructions for that in this repo

**Comment by LyubomirT** [comment]
Got it! I'll prepare a few versions of the logo (for different aspects) and will add a `branding/logo` directory via a Pull Request.

**Comment by TheMaster3558** [comment]
@LyubomirT could you actually create a new directory ``docs/_static/branding`` and add the logo there? In addition, you can add any credits to yourself in any reasonable places you see fit (for example the README) in your PR.

**Comment by LyubomirT** [comment]
Sure thing, I'll let you know when I'm done :D
